OBJS = Modern.cpp

CC = g++

COMPILER_FLAGS = -w -std=c++11

LINKER_FLAGS = -lGL -lglut -lGLU -lGLEW -lSDL2 -lSDL2_image -lSDL2_ttf

OBJ_NAME = Modern

all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
